# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DagMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DagMobile
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'

  target 'DagMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DagMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DagMobile-tvOS

  target 'DagMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
